name: local_storage
description: A local storage implementation using SharedPreferences, FlutterSecureStorage, or any other local storage implementation for Flutter applications.
version: 0.0.2
homepage: https://github.com/bienvenuelisis/local_storage
repository: https://github.com/bienvenuelisis/local_storage
issue_tracker: https://github.com/bienvenuelisis/local_storage/issues


environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0